AWSTemplateFormatVersion: '2010-09-09'
Description: 'Enterprise AWS Serverless Data Pipeline for Healthcare Claims Processing'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: healthcare-claims-pipeline
    Description: Project name for resource naming
  
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for VPC
  
  DataBucketName:
    Type: String
    Description: S3 bucket name for data storage (must be globally unique)
  
  GlueJobMaxCapacity:
    Type: Number
    Default: 100
    Description: Maximum DPU capacity for Glue jobs
  
  MonitoringEmail:
    Type: String
    Description: Email for monitoring alerts
    AllowedPattern: '^[^\s@]+@[^\s@]+\.[^\s@]+$'

Mappings:
  EnvironmentMap:
    dev:
      LogRetentionDays: 7
      BackupRetentionDays: 7
    staging:
      LogRetentionDays: 30
      BackupRetentionDays: 30
    prod:
      LogRetentionDays: 365
      BackupRetentionDays: 90

Resources:
  # VPC and Networking
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-vpc'
        - Key: Environment
          Value: !Ref Environment

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCidr, 4, 8]]
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-private-subnet-1'

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [1, !Cidr [!Ref VpcCidr, 4, 8]]
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-private-subnet-2'

  # S3 Buckets
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DataBucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldData
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
      NotificationConfiguration:
        CloudWatchConfigurations:
          - Event: s3:ObjectCreated:*
            CloudWatchConfiguration:
              LogGroupName: !Ref S3LogGroup
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DataBucketName}-processed'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # SNS Topics
  DataProcessingTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-data-processing'
      DisplayName: Data Processing Notifications
      KmsMasterKeyId: alias/aws/sns

  ErrorNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-error-notifications'
      DisplayName: Error Notifications
      KmsMasterKeyId: alias/aws/sns

  # SNS Subscriptions
  ErrorEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ErrorNotificationTopic
      Protocol: email
      Endpoint: !Ref MonitoringEmail

  # CloudWatch Log Groups
  S3LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/s3/${ProjectName}-${Environment}'
      RetentionInDays: !FindInMap [EnvironmentMap, !Ref Environment, LogRetentionDays]

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}'
      RetentionInDays: !FindInMap [EnvironmentMap, !Ref Environment, LogRetentionDays]

  GlueLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/glue/${ProjectName}-${Environment}'
      RetentionInDays: !FindInMap [EnvironmentMap, !Ref Environment, LogRetentionDays]

  # IAM Roles and Policies
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-lambda-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub '${DataBucket}/*'
                  - !Sub '${ProcessedDataBucket}/*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref DataProcessingTopic
                  - !Ref ErrorNotificationTopic
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-glue-service-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub '${DataBucket}/*'
                  - !GetAtt ProcessedDataBucket.Arn
                  - !Sub '${ProcessedDataBucket}/*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - !Ref DataProcessingTopic
                  - !Ref ErrorNotificationTopic

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${ProjectName}-${Environment}-vpc-id'

  DataBucketName:
    Description: Data bucket name
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-data-bucket'

  ProcessedDataBucketName:
    Description: Processed data bucket name
    Value: !Ref ProcessedDataBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-processed-data-bucket'

  DataProcessingTopicArn:
    Description: SNS topic ARN for data processing
    Value: !Ref DataProcessingTopic
    Export:
      Name: !Sub '${ProjectName}-${Environment}-data-processing-topic'

  ErrorNotificationTopicArn:
    Description: SNS topic ARN for error notifications
    Value: !Ref ErrorNotificationTopic
    Export:
      Name: !Sub '${ProjectName}-${Environment}-error-notification-topic'

  LambdaExecutionRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-lambda-role'

  GlueServiceRoleArn:
    Description: Glue service role ARN
    Value: !GetAtt GlueServiceRole.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-glue-role'
